
service: unicle

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: ap-northeast-1

package:
  exclude:
    - src/**
    - tsconfig.json
    - webpack.dev.conf.js
    - webpack.prod.conf.js
    - node_modules/.bin
    - node_modules/.bin/*

functions:
  update_articles:
    handler: dist/bundle.update_articles
    events:
      - http:
          path: update_articles
          method: post
  fetch:
    handler: dist/bundle.fetch
    events:
      - http:
          path: fetch
          method: get
          cors: true
